/**
 * Typed payloads for every domain event.
 * Every handler receives a strongly-typed payload — no any, no casting.
 */

// ── Base ─────────────────────────────────────────────────────────────────────

export interface BaseEvent {
  /** UUID v4 generated by the publisher */
  eventId: string;
  /** ISO-8601 timestamp of when the event was emitted */
  timestamp: string;
  /** School (tenant) this event belongs to */
  schoolId: string;
  /** Schema version, increment when payload shape changes */
  version: number;
}

// ── Student ───────────────────────────────────────────────────────────────────

export interface StudentEnrolledEvent extends BaseEvent {
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  academicYear: string;
  transportEnabled: boolean;
}

export interface StudentTransportUpdatedEvent extends BaseEvent {
  studentId: string;
  oldStatus: string;
  newStatus: string;
}

export interface StudentDeletedEvent extends BaseEvent {
  studentId: string;
}

// ── Admissions ────────────────────────────────────────────────────────────────

export interface AdmissionCreatedEvent extends BaseEvent {
  admissionId: string;
  studentName: string;
  classId: string;
  academicYear: string;
}

export interface AdmissionConfirmedEvent extends BaseEvent {
  admissionId: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  academicYear: string;
  parentName: string;
  parentEmail?: string;
  parentPhone?: string;
}

export interface AdmissionRejectedEvent extends BaseEvent {
  admissionId: string;
  studentName: string;
  reason?: string;
  parentEmail?: string;
}

// ── Fee / Finance ─────────────────────────────────────────────────────────────

export interface FeeStructureCreatedEvent extends BaseEvent {
  structureId: string;
  classId: string;
  academicYear: string;
  academicFee: number;
  transportFee: number;
  otherFee: number;
}

export interface FeeAssignedEvent extends BaseEvent {
  assignmentId: string;
  studentId: string;
  structureId: string;
  totalFee: number;
  dueDate: string;
  academicYear: string;
}

export interface FeePaymentCompletedEvent extends BaseEvent {
  paymentId: string;
  studentId: string;
  studentName: string;
  assignmentId: string;
  amount: number;
  receiptNo: string;
  paymentMode: string;
  paymentDate: string;
  parentEmail?: string;
  parentPhone?: string;
}

export interface FeePaymentFailedEvent extends BaseEvent {
  studentId: string;
  assignmentId: string;
  amount: number;
  reason: string;
}

export interface FeeOverdueEvent extends BaseEvent {
  studentId: string;
  studentName: string;
  assignmentId: string;
  dueAmount: number;
  dueDate: string;
  parentEmail?: string;
  parentPhone?: string;
}

// ── Attendance ────────────────────────────────────────────────────────────────

export interface AttendanceMarkedEvent extends BaseEvent {
  classId: string;
  date: string;
  presentCount: number;
  absentCount: number;
  totalStudents: number;
  absentStudentIds: string[];
}

export interface AttendanceAbsentEvent extends BaseEvent {
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  date: string;
  parentPhone?: string;
  parentEmail?: string;
}

export interface AttendanceLateEvent extends BaseEvent {
  studentId: string;
  studentName: string;
  classId: string;
  date: string;
  time: string;
  parentPhone?: string;
  parentEmail?: string;
}

// ── Exams ─────────────────────────────────────────────────────────────────────

export interface ExamCreatedEvent extends BaseEvent {
  examId: string;
  examName: string;
  classId: string;
  scheduledDate: string;
}

export interface ExamResultPublishedEvent extends BaseEvent {
  examId: string;
  examName: string;
  classId: string;
  publishedBy: string;
}

// ── Payroll ───────────────────────────────────────────────────────────────────

export interface PayrollGeneratedEvent extends BaseEvent {
  payrollId: string;
  month: string;
  year: number;
  totalAmount: number;
  staffCount: number;
}

export interface PayrollDisbursedEvent extends BaseEvent {
  payrollId: string;
  disbursedAt: string;
  totalAmount: number;
}

// ── School ────────────────────────────────────────────────────────────────────

export interface SchoolCreatedEvent extends BaseEvent {
  schoolName: string;
}

export interface SchoolDeletedEvent extends BaseEvent {
  schoolId: string;
}

// ── Notifications (cross-cutting) ─────────────────────────────────────────────

export type NotificationChannel = "email" | "sms" | "push" | "whatsapp";

export interface NotificationSendEvent extends BaseEvent {
  channel: NotificationChannel;
  to: string;
  subject: string;
  body: string;
  metadata?: Record<string, unknown>;
}

// ── Analytics ─────────────────────────────────────────────────────────────────

export interface AnalyticsTrackEvent extends BaseEvent {
  entity: string;
  action: string;
  entityId: string;
  metadata?: Record<string, unknown>;
}

// ── Event payload map (EventName → payload type) ──────────────────────────────
// Lets the bus infer payload types from event names.

import type { EventName } from "./eventNames";

export interface DomainEventMap {
  "student.enrolled":          StudentEnrolledEvent;
  "student.transferred":       StudentEnrolledEvent;
  "student.transport.updated": StudentTransportUpdatedEvent;
  "student.deleted":           StudentDeletedEvent;
  "admission.created":         AdmissionCreatedEvent;
  "admission.confirmed":       AdmissionConfirmedEvent;
  "admission.rejected":        AdmissionRejectedEvent;
  "fee.structure.created":     FeeStructureCreatedEvent;
  "fee.assigned":              FeeAssignedEvent;
  "fee.payment.completed":     FeePaymentCompletedEvent;
  "fee.payment.failed":        FeePaymentFailedEvent;
  "fee.overdue":               FeeOverdueEvent;
  "attendance.marked":         AttendanceMarkedEvent;
  "attendance.absent":         AttendanceAbsentEvent;
  "attendance.late":           AttendanceLateEvent;
  "exam.created":              ExamCreatedEvent;
  "exam.result.published":     ExamResultPublishedEvent;
  "payroll.generated":         PayrollGeneratedEvent;
  "payroll.disbursed":         PayrollDisbursedEvent;
  "school.created":            SchoolCreatedEvent;
  "school.deleted":            SchoolDeletedEvent;
  "notification.send":         NotificationSendEvent;
  "analytics.track":           AnalyticsTrackEvent;
}

export type PayloadOf<E extends EventName> =
  E extends keyof DomainEventMap ? DomainEventMap[E] : Record<string, unknown>;
